### ISSUE TITLE
Matching scores cannot be ints

### ISSUE THREAD

**Issue by cmacdonald** [cvangysel/pytrec_eval#6]
This works
`evaluator.evaluate({'151': {'clueweb09-en0027-05-20087': float(10000)}})`
This does not:
evaluator.evaluate({'151': {'clueweb09-en0027-05-20087': 10000}})

There's no valid reason why a matching score cannot be an int, so I think the check at https://github.com/cvangysel/pytrec_eval/blob/6440d7e07ef18443a7423e531368091aac474eb5/src/pytrec_eval.cpp#L270
is too strict.

The error message is not too clear:
`
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-36-95f9429f5278> in <module>()
----> 1 evaluator.evaluate({'151': {'clueweb09-en0027-05-20087': 10000}})

TypeError: Unable to extract query/object scores.
`

I think that the exact problem is being overwritten by the calling code that checks the return value.

**Comment by cvangysel** [comment]
I agree. Feel free to send a PR to fix this.

**Comment by cmacdonald** [comment]
PR sent a few days ago. Good to go?

**Comment by cvangysel** [comment]
Sorry for the delayed response. PR merged!

**Comment by nightlessbaron** [comment]
Just leaving this comment here in case this helps anyone else. I got this error while using `evaluator.evaluate()`. The reason I got the error was because one of my variable was of the type `np.float32` whereas I am assuming the builder expects it be of type `float`. Changing type to float resolved the error.
